name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test

  release:
    name: Build & Upload Release
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu

      - name: Add targets
        run: |
          rustup target add x86_64-unknown-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

      - name: Set VERSION from tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build Linux x86_64
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build Linux aarch64
        run: cargo build --release --target aarch64-unknown-linux-gnu

      - name: Install cross-compilation tools for macOS
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cross

      - name: Build macOS x86_64
        run: cross build --release --target x86_64-apple-darwin

      - name: Build macOS aarch64
        run: cross build --release --target aarch64-apple-darwin

      - name: Create release archives
        run: |
          mkdir -p dist/archives

          # Linux x86_64
          mkdir -p dist/tmp/linux-amd64
          cp target/x86_64-unknown-linux-gnu/release/codicat dist/tmp/linux-amd64/
          cp README.md dist/tmp/linux-amd64/
          tar -czf dist/archives/codicat-linux-amd64.tar.gz -C dist/tmp/linux-amd64 codicat README.md

          # Linux aarch64
          mkdir -p dist/tmp/linux-arm64
          cp target/aarch64-unknown-linux-gnu/release/codicat dist/tmp/linux-arm64/
          cp README.md dist/tmp/linux-arm64/
          tar -czf dist/archives/codicat-linux-arm64.tar.gz -C dist/tmp/linux-arm64 codicat README.md

          # macOS x86_64
          mkdir -p dist/tmp/darwin-amd64
          cp target/x86_64-apple-darwin/release/codicat dist/tmp/darwin-amd64/
          cp README.md dist/tmp/darwin-amd64/
          tar -czf dist/archives/codicat-darwin-amd64.tar.gz -C dist/tmp/darwin-amd64 codicat README.md

          # macOS aarch64
          mkdir -p dist/tmp/darwin-arm64
          cp target/aarch64-apple-darwin/release/codicat dist/tmp/darwin-arm64/
          cp README.md dist/tmp/darwin-arm64/
          tar -czf dist/archives/codicat-darwin-arm64.tar.gz -C dist/tmp/darwin-arm64 codicat README.md

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ env.VERSION }}"
          files: dist/archives/*.tar.gz
